services:
  - type: web
    name: learning-platform
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: HOST
        value: 0.0.0.0
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: MONGODB_URI
        # 需要在Render控制台设置MongoDB Atlas连接字符串
        # 格式: mongodb+srv://username:password@cluster.mongodb.net/learning_platform
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://learning-platform-lqy1.onrender.com
      - key: LOG_LEVEL
        value: info